### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by s3cur3** [velomapa/gpx_ex#2]
Hi there! First, let me say thank you for putting this together. It works great, and the code is exceptionally clean!

I was working on a PR to add support for standalone waypoints and routes for use in my company's mapping app, but we can't actually use it in production without an open source license. Would it be possible to add one?

**Comment by caspg** [comment]
@s3cur3  Hey. Thanks for the kind words :) Added the MIT License.

**Comment by s3cur3** [comment]
Sweet, thanks so much!
