### ISSUE TITLE
Length of Track Segments

### ISSUE THREAD

**Issue by atanasna** [velomapa/gpx_ex#5]
Hello, I've found your repo and have been happily using it on a personal project. However I was in need of calculating the length/distance of the segments in a gpx file. I've implemented this myself and was wondering if I can somehow open a PR to add it

**Comment by atanasna** [comment]
@caspg, thanks but I'm not sure how. It looks like I have neither permissions to push a branch nor to open a PR

**Comment by caspg** [comment]
@atanasna Can you fork this repo and open PR from there?

**Comment by atanasna** [comment]
Sorry for the stupid question, thanks for the lead :)
